version: 0.2
run-as: root

phases:
  install:
    commands:
      - n 16 # install node 16
      - npm install -g yarn
      - npm install -g serverless

  pre_build:
    commands:
      - composer install
      - yarn install

  build:
    commands:
      - yarn build
      - yarn install --prune

  post_build:
    commands:
      - aws s3 cp s3://${AWS_ENV_BUCKET}/node-express-serverless/.env .env
      - yarn deploy:prod

cache:
  paths:
    - node_modules/**/*
    - yarn.lock
    - vendor/**/*
    - composer.lock
